CREATE OR REPLACE PACKAGE VALIDADOR IS
--------------------------------------------------------------------------------------------------------
  FUNCTION GETVALORLETRA
  (
   pLETRA VARCHAR2
  )RETURN NUMBER;

  FUNCTION VALIDARMOVIMIENTO(
	pID_PARTIDA PARTIDAS.ID%TYPE,
	pID_POSICION_INICIO  POSICIONES.ID%TYPE,
	pID_POSICION_FINAL  POSICIONES.ID%TYPE
  )RETURN BOOLEAN;
 END VALIDADOR;
 --------------------------------------------------------------------------------------------------------
/

CREATE OR REPLACE PACKAGE BODY VALIDADOR IS
  FUNCTION GETVALORLETRA(
	pLETRA VARCHAR2
  ) RETURN NUMBER
  IS
  NUMEROLETRA NUMBER DEFAULT NULL;
  BEGIN
	  case  pLETRA
		when 'A' then
		 NUMEROLETRA := 1;
		when 'B' then
		 NUMEROLETRA := 2;
		when 'C' then
		 NUMEROLETRA := 3;
		when 'D' then
		 NUMEROLETRA := 4;
		when 'E' then
		 NUMEROLETRA := 5;
		when 'F' then
		 NUMEROLETRA := 6;
		when 'G' then
		 NUMEROLETRA := 7;
		when 'H' then
		 NUMEROLETRA := 8;
		when '1' then
		 NUMEROLETRA := 1;
		when '2' then
		 NUMEROLETRA := 2;
		when '3' then
		 NUMEROLETRA := 3;
		when '4' then
		 NUMEROLETRA := 4;
		when '5' then
		 NUMEROLETRA := 5;
		when '6' then
		 NUMEROLETRA := 6;
		when '7' then
		 NUMEROLETRA := 7;
		when '8' then
		 NUMEROLETRA := 8;
	  end case;
  RETURN NUMEROLETRA;
  END GETVALORLETRA;
 
  FUNCTION VALIDARMOVIMIENTO (
	pID_PARTIDA PARTIDAS.ID%TYPE,
	pID_POSICION_INICIO POSICIONES.ID%TYPE,
	pID_POSICION_FINAL POSICIONES.ID%TYPE
  ) RETURN BOOLEAN
  IS
    cursor getPosicion(pid number,pid_partid NUMBER) is select * from posiciones 
	where ID = pid AND ID_PARTIDA = pid_partid ;

	cursor getFicha(pid number) is select * from fichas where ID = pid;
	
	COLUMNAINICIO POSICIONES.COLUMNA%TYPE DEFAULT 'NULL';
	COLUMNAFINAL  POSICIONES.COLUMNA%TYPE DEFAULT 'NULL';
	FILAINICIO POSICIONES.FILA%TYPE DEFAULT 'NULL';
	FILAFINAL POSICIONES.FILA%TYPE DEFAULT 'NULL';
	TODOBIEN BOOLEAN DEFAULT FALSE;
	ID_FICHA_INICIO FICHAS.ID%TYPE DEFAULT NULL;
	ID_FICHA_FINAL FICHAS.ID%TYPE DEFAULT NULL;
	COLORFICHAINICIO FICHAS.COLOR%TYPE DEFAULT 'NULL';
	COLORFICHAFINAL FICHAS.COLOR%TYPE DEFAULT 'NULL';
	NOMBRE_FICHA_INICIO FICHAS.NOMBRE%TYPE DEFAULT 'NULL';
	NOMBRE_FICHA_FINAL FICHAS.NOMBRE%TYPE DEFAULT 'NULL';
	BEGIN
	for posicio in getPosicion(pID_POSICION_INICIO,pID_PARTIDA)loop
        COLUMNAINICIO := posicio.COLUMNA;
		FILAINICIO := posicio.FILA;
		ID_FICHA_INICIO := posicio.ID_FICHA;
	end loop;
	for posicio in getPosicion(pID_POSICION_FINAL,pID_PARTIDA)loop
        COLUMNAFINAL := posicio.COLUMNA;
		FILAFINAL := posicio.FILA;
		ID_FICHA_FINAL := posicio.ID_FICHA;
	end loop;
	for ficha in getFicha(ID_FICHA_INICIO)loop
		COLORFICHAINICIO := ficha.color;
		NOMBRE_FICHA_INICIO := ficha.nombre;
	end loop;
	for ficha in getFicha(ID_FICHA_FINAL)loop
		COLORFICHAFINAL := ficha.color;
		NOMBRE_FICHA_FINAL := ficha.nombre;
	end loop;
	case NOMBRE_FICHA_INICIO
	   when 'TORRE' then
		   begin
			 IF (COLUMNAINICIO = COLUMNAFINAL OR FILAINICIO = FILAFINAL) AND COLORFICHAINICIO != COLORFICHAFINAL THEN
				TODOBIEN := TRUE;
			 END IF;
		   end;
		when'ALFIL'then
			
IF(abs(FILAINICIO - FILAFINAL) = abs(GETVALORLETRA(COLUMNAINICIO) - GETVALORLETRA(COLUMNAFINAL))) AND ((COLORFICHAINICIO != COLORFICHAFINAL)) THEN
TODOBIEN := TRUE;
END IF;
			
		when'REINA'then
		   begin
			 IF((abs(FILAINICIO - FILAFINAL) = abs(GETVALORLETRA(COLUMNAINICIO) - GETVALORLETRA(COLUMNAFINAL)))
			 OR (COLUMNAINICIO = COLUMNAFINAL OR FILAINICIO = FILAFINAL)) AND (COLORFICHAINICIO != COLORFICHAFINAL) THEN
				TODOBIEN := TRUE;
			 END IF;
		   end;
		when 'REY' then
		   begin
			IF abs(FILAINICIO - FILAFINAL) <= 1  AND abs(GETVALORLETRA(COLUMNAINICIO) - GETVALORLETRA(COLUMNAFINAL)) <= 1 AND COLORFICHAINICIO != COLORFICHAFINAL THEN
				TODOBIEN := TRUE;
			 END IF;
		   end;
		when 'PEON' then
		   begin
			 IF abs(FILAINICIO - FILAFINAL) = 1  THEN
				IF COLORFICHAINICIO = 'BLANCAS' AND FILAINICIO < FILAFINAL OR COLORFICHAINICIO = 'NEGRAS' AND FILAINICIO > FILAFINAL THEN
				   TODOBIEN := TRUE;
				   IF abs(GETVALORLETRA(COLUMNAINICIO) - GETVALORLETRA(COLUMNAFINAL)) = 1 THEN
						case COLORFICHAINICIO
						   when 'BLANCAS' then
							   IF COLORFICHAFINAL = 'NEGRAS' THEN
								 TODOBIEN := TRUE;
								ELSE
								 TODOBIEN := FALSE;
							   END IF;
						   when 'NEGRAS' then
							   IF COLORFICHAFINAL = 'BLANCAS' THEN
								 TODOBIEN := TRUE;
							   ELSE
								 TODOBIEN := FALSE;
							   END IF;
						   else
						    TODOBIEN := FALSE;
						end case;
				   END IF;
				END IF;
			 END IF;
		   end;
		 when 'CABALLO' then
		   begin 
			 IF abs(FILAINICIO - FILAFINAL) * abs(FILAINICIO - FILAFINAL) + abs(GETVALORLETRA(COLUMNAINICIO) - GETVALORLETRA(COLUMNAFINAL)) * abs(GETVALORLETRA(COLUMNAINICIO) - GETVALORLETRA(COLUMNAFINAL)) = 5
			 AND COLORFICHAINICIO != COLORFICHAFINAL
			 THEN
				TODOBIEN := TRUE;
			 END IF;
		   end;
	    else
		 TODOBIEN := FALSE;
	end case;
  RETURN TODOBIEN;
  END VALIDARMOVIMIENTO;
END VALIDADOR;
/